try {let a;
console.log(a.length);
}catch(err){
    console.log("enter the catch statement");
}

console.log("outside the catch statements");